---
linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - exportloopref
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - importas
    - misspell
