#!/bin/sh
set -e
set -u

setcap cap_net_bind_service=+ep /opt/roxy/bin/roxy

if ! getent group roxy >/dev/null 2>&1 ; then
  addgroup --system --gid 400 roxy
fi

if ! getent passwd roxy >/dev/null 2>&1 ; then
  adduser --system --home /var/lib/roxy --no-create-home --uid 400 --gecos roxy --gid 400 --disabled-password roxy
fi

if ! [ -e /etc/opt/roxy/config.json ]; then
  cp /etc/opt/roxy/config.json.example /etc/opt/roxy/config.json
fi

if ! [ -e /etc/opt/roxy/mime.json ]; then
  cp /etc/opt/roxy/mime.json.example /etc/opt/roxy/mime.json
fi

chown root:roxy /etc/opt/roxy/config.json
chmod 0640 /etc/opt/roxy/config.json

chown roxy:roxy /var/opt/roxy/lib /var/opt/roxy/lib/acme
chmod 0750 /var/opt/roxy/lib /var/opt/roxy/lib/acme
