name: "Debian packages"
on:
  push:
    tags: "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        env:
          RELEASE_MODE: true
        run: ${GITHUB_WORKSPACE}/build_deb.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release-notes.txt
          body: "New release."
          files: |
            *.deb
          fail_on_unmatched_files: true
