name: Go

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.version'
      - 'Dockerfile*'
      - '**.md'
      - '**.sh'
      - '**.txt'
      - '**.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.version'
      - 'Dockerfile*'
      - '**.md'
      - '**.sh'
      - '**.txt'
      - '**.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v ./...
