name: golangci-lint
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
    paths-ignore:
      - '.version'
      - 'Dockerfile*'
      - '**.md'
      - '**.sh'
      - '**.txt'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.version'
      - 'Dockerfile*'
      - '**.md'
      - '**.sh'
      - '**.txt'
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.48.0
          only-new-issues: true
