name: "Release"
on:
  push:
    tags: "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Docker login
        run: 'echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin'

      - name: Docker build
        env:
          RELEASE_MODE: true
        run: ${GITHUB_WORKSPACE}/build_docker.sh

      - name: Debian build
        env:
          RELEASE_MODE: true
        run: ${GITHUB_WORKSPACE}/build_deb.sh

      - name: Prepare release notes
        run: ${GITHUB_WORKSPACE}/build_relnotes.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: release-notes.txt
          files: |
            *.deb
